[project]
name = "readyoneweb"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "python-dotenv>=1.2.1",
    "streamlit>=1.52.1",
    "supabase>=2.25.1",
]
